// <auto-generated />
namespace SimpleShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Second_layer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Second_layer));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161617329_Second_layer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
