// <auto-generated />
namespace SimpleShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class onetooneaddadres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onetooneaddadres));
        
        string IMigrationMetadata.Id
        {
            get { return "201807020935176_one to one add adres "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
